18-auth/ripe_potatoes/config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  
  resources :movies
  resources :users, except: [:edit, :update ]
  resources :reviews, only: [:new, :create]

  delete '/sessions/reset_page_count', to: 'sessions#reset_page_view_cookie', as: 'page_reset'
  delete '/sessions/logout', to: 'sessions#logout', as: 'logout'
  get '/sessions/new', to: 'sessions#new', as: 'new_login'
  post '/sessions/create', to: 'sessions#create', as: 'login'

  # get '/movies', to: 'movies#index', as: 'movies'
  # get '/movies/new', to: 'movies#new', as: 'new_movie'
  # get '/movies/:id', to: 'movies#show', as: 'movie'
  # get '/movies/:id/edit', to: 'movies#edit', as: 'edit_movie'

  # post '/movies', to: 'movies#create'
  # patch '/movies/:id', to: 'movies#update'
end

18-auth/ripe_potatoes/app/models/review.rb
class Review < ApplicationRecord
  belongs_to :user, optional: true
  belongs_to :movie


  validates :rating, numericality: {greater_than: 0, less_than_or_equal_to: 10}
  validates :content, :rating, presence: {message: 'gotta be there'}
  validates :content, length:  {maximum: 500}
  validates :user, uniqueness: {scope: :movie_id}

  # validate :some_custom_method
  
end

18-auth/ripe_potatoes/app/models/user.rb
class User < ApplicationRecord
  has_many :reviews
  has_many :movies, through: :reviews

  has_secure_password

  # def password=(secret)
  #   hashed_password = BCrypt::Password.create(secret)
  #   self.password_digest = hashed_password 
  # end

  # def password 
  # end
end

18-auth/ripe_potatoes/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :set_current_user
  before_action :authorized

  def set_current_user
    # @current_user = User.find(session[:user_id])
    @current_user = User.find_by(id: session[:user_id])
  end 

  def authorized
    redirect_to new_login_path unless set_current_user 
  end 

end

18-auth/ripe_potatoes/app/controllers/movies_controller.rb
class MoviesController < ApplicationController
  before_action :find_movie, only: [:show, :edit, :update, :destroy]
  skip_before_action :authorized, only: [:index]

  def index 
    # byebug
    @movies = Movie.all

    # render :index
  end 


  def show 
    # @movie = Movie.find(params[:id])
    if session[:view_count]
      session[:view_count] = session[:view_count] + 1
    else 
      session[:view_count] = 1
    end 

  end 
  
  def new 
    @movie = Movie.new
  end 
  
  def create
    movie = Movie.create(movie_params)
    
    redirect_to movie_path(movie) # get /movies/7
  end 

  def edit 
    # @movie = Movie.find(params[:id])
  end 

  
  def update 
    # @movie = Movie.find(params[:id])
    @movie.update(movie_params)
    
    redirect_to movie_path(@movie)
  end 
  
  def destroy 
    # @movie = Movie.find(params[:id])
    @movie.destroy
    
    redirect_to movies_path
  end 
  
  private 
  
  def movie_params 
    params.require(:movie).permit(:title, :genre, :year)
  end 

  def find_movie 
    @movie = Movie.find(params[:id])
  end 

end

18-auth/ripe_potatoes/app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  def new 
    @review = Review.new

    @movies = Movie.all
    @users = User.all
  end 

  def create 
    @review = @current_user.reviews.create(review_params)
    # @review = Review.new(review_params)

      #  @review.save
    if @review.valid?
      redirect_to user_path(@review.user_id)
    else 
      flash[:my_errors] =  @review.errors.full_messages

      redirect_to new_review_path
    end 
    # redirect_to user_path(@review.user)
  end 

  private

  def review_params
    params.require(:review).permit(:movie_id, :rating, :content)
  end 

end

18-auth/ripe_potatoes/app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  skip_before_action :authorized, only: [:new, :create]

  def reset_page_view_cookie
    # cookies[:view_count] = nil
    session.delete(:view_count)

    redirect_back fallback_location: movies_path
  end 

  def new 
  end

  def create 
    user = User.find_by(name: params[:session][:name])

    if user && user.authenticate(params[:session][:password])
      session[:user_id] = user.id 
      redirect_to user 
    else 
      flash[:error] = "username or password is incorrect"
      redirect_to new_login_path
    end

  end 


  def logout 
    # session[:user_id] = nil
    session.delete(:user_id)

    redirect_to new_user_path
  end 
end

18-auth/ripe_potatoes/app/controllers/users_controller.rb
class UsersController < ApplicationController
  skip_before_action :authorized, only: [:new, :create]
  def index
    @users = User.all
  end 

  def show 
    @user = User.find(params[:id])

    if @user == @current_user
      render :show
    else 
      flash[:error] = "can only see your profile"
      redirect_to users_path
    end 

  end 

  def new 
    @user = User.new
  end 

  def create 
    user = User.create(user_params)

    if user.valid? 
      session[:user_id] =  user.id
      redirect_to user
    else
      flash[:errors] = user.errors.full_messages
      redirect_to new_user_path
    end 
  end 

  def destroy
    user = User.find(params[:id])
    user.destroy
    
    redirect_to users_path
  end 

  private 

  def user_params 
    params.require(:user).permit(:name, :age, :slogan, :img_url, :password)
  end 
end

18-auth/ripe_potatoes/app/helpers/application_helper.rb
module ApplicationHelper
end

18-auth/ripe_potatoes/app/helpers/favorites_helper.rb
module FavoritesHelper
end

18-auth/ripe_potatoes/app/helpers/movies_helper.rb
module MoviesHelper
end

18-auth/ripe_potatoes/app/helpers/sessions_helper.rb
module SessionsHelper
end

18-auth/ripe_potatoes/app/helpers/users_helper.rb
module UsersHelper
end

18-auth/ripe_potatoes/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RipePotatoes</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
      <div class='nav'>
        <%# <span><h1>Movie Magic</h1></span> %>
        <img class='logo' src="https://secureimg.stitcher.com/feedimagesplain328/168515.jpg" alt="mm">
      </div>

      <ul>
        <li><%= link_to 'Movie Home', movies_path %></li>
        <li><%= link_to 'User Home', users_path %></li>
        <li><%= link_to 'New Movie', new_movie_path %></li>

        <% if @current_user %>
          <li class='right'>Welcome <%= @current_user.name %>!</li>
          <li class='right'><%= link_to "Log-Out", logout_path, method: :delete%></li>
        <% else %>
          <li class='right'><%= link_to 'Sign-Up', new_user_path %></li>
          <li class='right'><%= link_to 'Sign-In', new_login_path %></li>
        <% end %>
      </ul>

    <%= yield %>
  </body>
</html>

18-auth/ripe_potatoes/app/views/movies/_form.html.erb
<%= form_for @movie do |f| %>
  <%= f.label :title %>
  <%= f.text_field :title %>

  <%= f.label :overview %>
  <%= f.text_field :overview %>

  <%= f.label :year %>
  <%= f.number_field :year %>
  
  <%= f.submit %>
<% end %>

18-auth/ripe_potatoes/app/views/movies/edit.html.erb
<h1>Edit Movie</h1>


<%= render 'form' %>

18-auth/ripe_potatoes/app/views/movies/index.html.erb
<h1>Movie Index Page</h1>

<div class="index-container">
  <% @movies.each do |movie| %>
    <div class="index-tile">
      <h3><%= link_to movie.title, movie_path(movie.id)  %></h3>
      <h5>Release Year: <%= movie.year %></h5>
      
      <img class="index-img" src="<%= movie.img_url %>" alt="<%= movie.title%>">

      <hr>
      <h6>API Vote Count: <%= movie.vote_count %></h6>
      <h6>API Average Vote: <%= movie.vote_average %></h6>
      <% if @current_user %>
        <%= button_to "X", movie_path(movie), method: :delete %>
      <% end %>
    </div>
  <% end %>
</div>

18-auth/ripe_potatoes/app/views/movies/new.html.erb
<h1>New Movie Form</h1>

<%= render 'form' %>

18-auth/ripe_potatoes/app/views/movies/show.html.erb
<div class="show-body">
    <% if  session[:view_count] <= 3 %>
        <h1 style="color: green;">You have <%= 3 - session[:view_count].to_i %> view left</h1>
        <h2><%= @movie.title %></h2>
        <p><%= @movie.overview %></p>


        <marquee scrolldelay='60'><img class="show-img" src="<%= @movie.img_url %>" alt="<%= @movie.title%>"></marquee> 

        <h6>Vote Count: <%= @movie.vote_count %></h6>
        <h6>Vote Average: <%= @movie.vote_average %></h6>

        <span><%= link_to "MOViES HOME", movies_path %></span>
    <% else %>
        <h1>Show Some Ad</h1>
        <iframe width="966" height="543" src="https://www.youtube.com/embed/dQw4w9WgXcQ" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>

        <%= button_to "I Prmise I got Rolled", page_reset_path, method: :delete %>
    <% end %>
</div>

18-auth/ripe_potatoes/app/views/reviews/new.html.erb
<h1>Create Review</h1>

<% if flash[:my_errors] %>
  <% flash[:my_errors].each do |error| %>
    <p style="color: yellow;"><%= error %></p>
  <% end %>
<% end %>

<%= form_for @review do |f| %>

  <%= f.label :movie_id %>
  <%= f.collection_select :movie_id, @movies, :id, :title %>

  <%= f.label :content %>
  <%= f.text_field :content %>

  <%= f.label :rating %>
  <%= f.number_field :rating %>

  <%= f.submit %>
<% end %>

18-auth/ripe_potatoes/app/views/users/index.html.erb
<h1>Movie Index Page</h1>

<% if flash[:error] %>
  <p><%= flash[:error] %></p>
<% end %>

<div class="index-container">
  <% @users.each do |user| %>
    <div class="index-tile">
      <h3><%= link_to user.name, user_path(user.id)  %></h3>
      
      <img class="index-img" src="<%= user.img_url %>" alt="<%= user.name%>">
      
      <%= button_to "X", user_path(user), method: :delete %>
    </div>
  <% end %>
</div>

18-auth/ripe_potatoes/app/views/users/new.html.erb
<h1>New User</h1>

<%= form_for @user do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>

  <%= f.label :password %>
  <%= f.text_field :password %>

  <%= f.label :age %>
  <%= f.number_field :age %>

  <%= f.label :slogan %>
  <%= f.text_field :slogan %>

  <%= f.label :img_url %>
  <%= f.text_field :img_url %>

  <%= f.submit %>
<% end %>

18-auth/ripe_potatoes/app/views/users/show.html.erb
<div class="show-body">
  <h1>User Show</h1>

  <h4><%= @user.name %></h4>
  <p><%= @user.age %></p>
  <p><%= @user.slogan %></p>
  <img class="show-img" src="<%= @user.img_url %>" alt="<%= @user.name%>">

  <h1>My Reviews</h1>

  <% @user.reviews.each do |review| %>
    <h3><%= link_to review.movie.title, movie_path(review.movie) %></h3>
    <p><%= review.content %> || <%= review.rating %></p>
    <hr>
  <% end  %>
</div>